### ISSUE TITLE
What is N-D data?

### ISSUE THREAD

**Issue by xiaobrnbrn** [cjekel/similarity_measures#13]
Hello, could you please explain what is N-D data?

**Comment by cjekel** [comment]
A lot of time when you see methods like Frechet distance, it only supports 2D data, ie matching the curve on a piece of paper. 

These methods inherently work in 1D, 2D, 3D, 4D, ..., ND. So 3D data would be the path history of a car (latitude , longitude, elevation), 4D would be like (x,y,z, time), and so forth.

Does this make sense?

The reason I state it explicitly is that some methods only work in 2D.

**Comment by xiaobrnbrn** [comment]
> A lot of time when you see methods like Frechet distance, it only supports 2D data, ie matching the curve on a piece of paper.
> 
> These methods inherently work in 1D, 2D, 3D, 4D, ..., ND. So 3D data would be the path history of a car (latitude , longitude, elevation), 4D would be like (x,y,z, time), and so forth.
> 
> Does this make sense?
> 
> The reason I state it explicitly is that some methods only work in 2D.

Thanks a lot!
