### ISSUE TITLE
The name of this repository is ridiculously long

### ISSUE THREAD

**Issue by nbro** [cjekel/similarity_measures#2]
Why not calling this repo only e.g. `similarity-measures`?

**Comment by cjekel** [comment]
I can do that. Initially this was just a couple jupyter notebooks reproducing the work of the paper, but now it's a bit silly.

I'll need to
[ ] new pypi release with updated homepage
[ ] fix website links
[ ] make old placeholder library to redirect

**Comment by cjekel** [comment]
Thanks for pointing this out. I changed the name to ```similarity_measures```.
